spring.application.name=customer-management-service
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Biswajit@408
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true

# JWT (we'll use these in Step 3)
app.jwt.secret=CHANGE-ME-TO-A-VERY-LONG-RANDOM-256-BIT-SECRET
app.jwt.ttl-seconds=3600
logging.level.org.springframework.security=DEBUG
logging.level.com.example.customer=DEBUG